<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
    <PackageVersion Include="Esatto.Utilities" Version="3.0.22" />
    <PackageVersion Include="Esatto.Win32.Com" Version="3.0.22" />
    <PackageVersion Include="Esatto.Win32.Common" Version="3.0.22" />
    <PackageVersion Include="Esatto.Win32.CommonControls" Version="3.0.22" />
    <PackageVersion Include="Esatto.Win32.Registry" Version="3.0.22" />
    <PackageVersion Include="Esatto.Win32.Registry.AdmxExporter" Version="3.0.22" />
    <PackageVersion Include="Esatto.Win32.RdpDvc.Common" Version="3.0.22" />
    <PackageVersion Include="System.Text.Json" Version="10.0.8" />
    <PackageVersion Include="dSPACE.Runtime.InteropServices.BuildTasks" Version="2.5.3" />
  </ItemGroup>
</Project>