<Project>
  <PropertyGroup>
    <Authors>mgaffigan</Authors>
    <Company>In Touch Technologies</Company>
    <Copyright>© 2022 In Touch Technologies.  All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <RepositoryUrl>https://github.com/mgaffigan/Esatto.AppCoord</RepositoryUrl>
    <PackageProjectUrl>https://github.com/mgaffigan/Esatto.AppCoord</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <VersionPrefix>5.2.0</VersionPrefix>
  </PropertyGroup>
</Project>